<a href="https://colab.research.google.com/github/iuliastremciuc/DS-Unit-2-Linear-Models/blob/master/module2-regression-2/IS_212_LS_DS_212_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 2*

---

# Regression 2

## Assignment

You'll continue to **predict how much it costs to rent an apartment in NYC,** using the dataset from renthop.com.

- [x] Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
- [x] Engineer at least two new features. (See below for explanation & ideas.)
- [x] Fit a linear regression model with at least two features.
- [x] Get the model's coefficients and intercept.
- [x] Get regression metrics RMSE, MAE, and $R^2$, for both the train and test data.
- [x] What's the best test MAE you can get? Share your score and features used with your cohort on Slack!
- [x] As always, commit your notebook to your fork of the GitHub repo.


#### [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)

> "Some machine learning projects succeed and some fail. What makes the difference? Easily the most important factor is the features used." — Pedro Domingos, ["A Few Useful Things to Know about Machine Learning"](https://homes.cs.washington.edu/~pedrod/papers/cacm12.pdf)

> "Coming up with features is difficult, time-consuming, requires expert knowledge. 'Applied machine learning' is basically feature engineering." — Andrew Ng, [Machine Learning and AI via Brain simulations](https://forum.stanford.edu/events/2011/2011slides/plenary/2011plenaryNg.pdf) 

> Feature engineering is the process of using domain knowledge of the data to create features that make machine learning algorithms work. 

#### Feature Ideas
- Does the apartment have a description?
- How long is the description?
- How many total perks does each apartment have?
- Are cats _or_ dogs allowed?
- Are cats _and_ dogs allowed?
- Total number of rooms (beds + baths)
- Ratio of beds to baths
- What's the neighborhood, based on address or latitude & longitude?

## Stretch Goals
- [ ] If you want more math, skim [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf),  Chapter 3.1, Simple Linear Regression, & Chapter 3.2, Multiple Linear Regression
- [x] If you want more introduction, watch [Brandon Foltz, Statistics 101: Simple Linear Regression](https://www.youtube.com/watch?v=ZkjP5RJLQF4)
(20 minutes, over 1 million views)
- [ ] Add your own stretch goal(s) !

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import numpy as np
import pandas as pd

# Read New York City apartment rental listing data
df = pd.read_csv(DATA_PATH+'apartments/renthop-nyc.csv')
assert df.shape == (49352, 34)

# Remove the most extreme 1% prices,
# the most extreme .1% latitudes, &
# the most extreme .1% longitudes
df = df[(df['price'] >= np.percentile(df['price'], 0.5)) & 
        (df['price'] <= np.percentile(df['price'], 99.5)) & 
        (df['latitude'] >= np.percentile(df['latitude'], 0.05)) & 
        (df['latitude'] < np.percentile(df['latitude'], 99.95)) &
        (df['longitude'] >= np.percentile(df['longitude'], 0.05)) & 
        (df['longitude'] <= np.percentile(df['longitude'], 99.95))]

In [114]:
df.head()

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [0]:
df = df.replace({'interest_level': {'low': 0, 'medium': 1, 'high': 2}})

In [117]:
df.head()

bathrooms  bedrooms  ... wheelchair_access common_outdoor_space
0        1.5         3  ...                 0                    0
1        1.0         2  ...                 0                    0
2        1.0         1  ...                 0                    0
3        1.0         1  ...                 0                    0
4        1.0         4  ...                 0                    0

[5 rows x 34 columns]

In [0]:
df['created'] = pd.to_datetime(df['created'], infer_datetime_format=True)

In [0]:
#Do train/test split. Use data from April & May 2016 to train. Use data from June 2016 to test.
train = df[df['created'].dt.month < 6]
test = df[df['created'].dt.month == 6]
          

In [132]:
train['price'].mean()

3575.604007034292

In [0]:
# Engineer at least two new features. (See below for explanation & ideas.)
features = ['longitude', 'latitude', 'bedrooms', 'bathrooms', 'interest_level', 'elevator', 'no_fee', 'pre-war']
target = 'price'
X_train = train[features]
X_test = test[features]
y_train = train[target]
y_test = test[target]

In [146]:
#Fit a linear regression model with at least two features.
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [147]:
train_predict = regression.predict(X_train)
train_predict

array([2438.41386803, 2879.24029099, 4032.09643535, ..., 3480.45153998,
       3232.83184193, 2762.1354805 ])

In [148]:
test_predict = regression.predict(X_test)
test_predict


array([3881.24751193, 3742.98670008, 2582.80681165, ..., 2784.17944644,
       3358.38621127, 3400.81559783])

In [149]:
#Get the model's coefficients and intercept.
regression.intercept_ , regression.coef_

(-1121215.1240935165,
 array([-1.44871407e+04,  1.23135935e+03,  4.72933501e+02,  1.85698323e+03,
        -4.57484502e+02,  3.56335979e+02,  1.27539110e+00, -8.45470040e+01]))

In [150]:
#Get regression metrics RMSE, MAE, and  R2 , for both the train and test data
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# Mean absolute error
mae_train = mean_absolute_error(y_train, train_predict)
mae_test = mean_absolute_error(y_test, test_predict)
# Mean squard error
mse_train = mean_squared_error(y_train, train_predict)
mse_test = mean_squared_error(y_test, test_predict)
# Root mean squared error
rmse_train = np.sqrt(mse_train)
rmse_test = np.sqrt(mse_test)
# R2 score
r2_train = r2_score(y_train, train_predict)
r2_test = r2_score(y_test, test_predict)
print(f'MAE_train: {mae_train};   MAE_test: {mae_test}')
print(f'RMSE_train: {rmse_train};   RMSE_test: {rmse_test}')
print(f'R2_train: {r2_train}:   R2_test: {r2_test}')

MAE_train: 696.1292622542305;   MAE_test: 700.0956080768452
RMSE_train: 1097.7078737476245;   RMSE_test: 1081.055679038274
R2_train: 0.6119318435998392:   R2_test: 0.6239789626702311


In [0]:
#What's the best test MAE you can get? Share your score and features used with your cohort on Slack!