<a href="https://colab.research.google.com/github/iuliastremciuc/DS-Unit-2-Linear-Models/blob/master/module3-ridge-regression/IS_213_LS_DS_213_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 1, Module 3*

---

# Ridge Regression

## Assignment

We're going back to our other **New York City** real estate dataset. Instead of predicting apartment rents, you'll predict property sales prices.

But not just for condos in Tribeca...

- [ ] Use a subset of the data where `BUILDING_CLASS_CATEGORY` == `'01 ONE FAMILY DWELLINGS'` and the sale price was more than 100 thousand and less than 2 million.
- [ ] Do train/test split. Use data from January — March 2019 to train. Use data from April 2019 to test.
- [ ] Do one-hot encoding of categorical features.
- [ ] Do feature selection with `SelectKBest`.
- [ ] Fit a ridge regression model with multiple features. Use the `normalize=True` parameter (or do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html) beforehand — use the scaler's `fit_transform` method with the train set, and the scaler's `transform` method with the test set)
- [ ] Get mean absolute error for the test set.
- [ ] As always, commit your notebook to your fork of the GitHub repo.

The [NYC Department of Finance](https://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page) has a glossary of property sales terms and NYC Building Class Code Descriptions. The data comes from the [NYC OpenData](https://data.cityofnewyork.us/browse?q=NYC%20calendar%20sales) portal.


## Stretch Goals

Don't worry, you aren't expected to do all these stretch goals! These are just ideas to consider and choose from.

- [ ] Add your own stretch goal(s) !
- [ ] Instead of `Ridge`, try `LinearRegression`. Depending on how many features you select, your errors will probably blow up! 💥
- [ ] Instead of `Ridge`, try [`RidgeCV`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html).
- [ ] Learn more about feature selection:
    - ["Permutation importance"](https://www.kaggle.com/dansbecker/permutation-importance)
    - [scikit-learn's User Guide for Feature Selection](https://scikit-learn.org/stable/modules/feature_selection.html)
    - [mlxtend](http://rasbt.github.io/mlxtend/) library
    - scikit-learn-contrib libraries: [boruta_py](https://github.com/scikit-learn-contrib/boruta_py) & [stability-selection](https://github.com/scikit-learn-contrib/stability-selection)
    - [_Feature Engineering and Selection_](http://www.feat.engineering/) by Kuhn & Johnson.
- [ ] Try [statsmodels](https://www.statsmodels.org/stable/index.html) if you’re interested in more inferential statistical approach to linear regression and feature selection, looking at p values and 95% confidence intervals for the coefficients.
- [ ] Read [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf), Chapters 1-3, for more math & theory, but in an accessible, readable way.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

In [0]:
import pandas as pd
import pandas_profiling

# Read New York City property sales data
df = pd.read_csv(DATA_PATH+'condos/NYC_Citywide_Rolling_Calendar_Sales.csv')

# Change column names: replace spaces with underscores
df.columns = [col.replace(' ', '_') for col in df]

# SALE_PRICE was read as strings.
# Remove symbols, convert to integer
df['SALE_PRICE'] = (
    df['SALE_PRICE']
    .str.replace('$','')
    .str.replace('-','')
    .str.replace(',','')
    .astype(int)
)

In [0]:
# BOROUGH is a numeric column, but arguably should be a categorical feature,
# so convert it from a number to a string
df['BOROUGH'] = df['BOROUGH'].astype(str)

In [0]:
# Reduce cardinality for NEIGHBORHOOD feature

# Get a list of the top 10 neighborhoods
top10 = df['NEIGHBORHOOD'].value_counts()[:10].index

# At locations where the neighborhood is NOT in the top 10, 
# replace the neighborhood with 'OTHER'
df.loc[~df['NEIGHBORHOOD'].isin(top10), 'NEIGHBORHOOD'] = 'OTHER'

In [0]:
print(df.shape)
df.head(10)

(23040, 21)


BOROUGH             NEIGHBORHOOD  ... SALE_PRICE   SALE_DATE
0       1                    OTHER  ...          0  01/01/2019
1       1                    OTHER  ...          0  01/01/2019
2       1                    OTHER  ...          0  01/01/2019
3       1                    OTHER  ...          0  01/01/2019
4       1  UPPER EAST SIDE (59-79)  ...          0  01/01/2019
5       1  UPPER EAST SIDE (79-96)  ...          0  01/01/2019
6       1                    OTHER  ...          0  01/01/2019
7       2                    OTHER  ...          0  01/01/2019
8       2                    OTHER  ...          0  01/01/2019
9       2                    OTHER  ...          0  01/01/2019

[10 rows x 21 columns]

In [0]:
df.describe()

BLOCK           LOT  ...  TAX_CLASS_AT_TIME_OF_SALE    SALE_PRICE
count  23040.000000  23040.000000  ...               23040.000000  2.304000e+04
mean    4459.116493    353.948481  ...                   1.624479  1.328133e+06
std     3713.269887    628.025255  ...                   0.803898  1.025394e+07
min        1.000000      1.000000  ...                   1.000000  0.000000e+00
25%     1341.000000     22.000000  ...                   1.000000  0.000000e+00
50%     3546.000000     49.000000  ...                   1.000000  4.550000e+05
75%     6673.750000    375.000000  ...                   2.000000  8.750000e+05
max    16350.000000   9057.000000  ...                   4.000000  8.500000e+08

[8 rows x 11 columns]

In [0]:
#Use a subset of the data where BUILDING_CLASS_CATEGORY == '01 ONE FAMILY DWELLINGS' and the sale price was more than 100 thousand and less than 2 million.
df = df[df['BUILDING_CLASS_CATEGORY'] == '01 ONE FAMILY DWELLINGS']
condition = ((df['SALE_PRICE'] > 100000) & (df['SALE_PRICE'] < 2000000))
df_subset = df[condition]
df_subset.head(10)


BOROUGH    NEIGHBORHOOD  ... SALE_PRICE   SALE_DATE
44        3           OTHER  ...     550000  01/01/2019
61        4           OTHER  ...     200000  01/01/2019
78        2           OTHER  ...     810000  01/02/2019
108       3           OTHER  ...     125000  01/02/2019
111       3           OTHER  ...     620000  01/02/2019
120       3           OTHER  ...    1150000  01/02/2019
121       3           OTHER  ...     836500  01/02/2019
132       4           OTHER  ...     955000  01/02/2019
137       4           OTHER  ...     820000  01/02/2019
141       4  FLUSHING-NORTH  ...     980000  01/02/2019

[10 rows x 21 columns]

In [0]:
df_subset.describe()

BLOCK          LOT  ...  TAX_CLASS_AT_TIME_OF_SALE    SALE_PRICE
count   3151.000000  3151.000000  ...                     3151.0  3.151000e+03
mean    6917.976515    75.981593  ...                        1.0  6.285601e+05
std     3963.326705   161.089514  ...                        0.0  2.929904e+05
min       21.000000     1.000000  ...                        1.0  1.040000e+05
25%     4016.000000    21.000000  ...                        1.0  4.475000e+05
50%     6301.000000    42.000000  ...                        1.0  5.680000e+05
75%    10208.500000    69.000000  ...                        1.0  7.600000e+05
max    16350.000000  2720.000000  ...                        1.0  1.955000e+06

[8 rows x 11 columns]

In [0]:
df_subset = df_subset.drop(['APARTMENT_NUMBER', 'BUILDING_CLASS_CATEGORY', 'EASE-MENT', 'ZIP_CODE', 'TAX_CLASS_AT_TIME_OF_SALE', 'BLOCK', 'LOT'], axis = 1)

In [0]:
df_subset.shape

(3151, 14)

In [0]:
df_subset.isnull().sum()

BOROUGH                           0
NEIGHBORHOOD                      0
TAX_CLASS_AT_PRESENT              0
BUILDING_CLASS_AT_PRESENT         0
ADDRESS                           0
RESIDENTIAL_UNITS                 0
COMMERCIAL_UNITS                  0
TOTAL_UNITS                       0
LAND_SQUARE_FEET                  0
GROSS_SQUARE_FEET                 0
YEAR_BUILT                        0
BUILDING_CLASS_AT_TIME_OF_SALE    0
SALE_PRICE                        0
SALE_DATE                         0
dtype: int64

In [0]:
df_subset['SALE_DATE'].describe()

count           3151
unique            91
top       01/31/2019
freq              78
Name: SALE_DATE, dtype: object

In [0]:
#Do train/test split. Use data from January — March 2019 to train. Use data from April 2019 to test.
df_subset['SALE_DATE'] = pd.to_datetime(df_subset['SALE_DATE'], infer_datetime_format=True)
train = df_subset[df_subset['SALE_DATE'].dt.month < 4]
test = df_subset[df_subset['SALE_DATE'].dt.month == 4]
          


In [0]:
train['SALE_PRICE'].mean()

621573.7423214999

In [0]:
print(train.shape)
print(test.shape)

(2507, 14)
(644, 14)


In [0]:
#Do one-hot encoding of categorical features
train.describe(exclude = 'number').T.sort_values(by = 'unique')

count unique  ...      first       last
TAX_CLASS_AT_PRESENT            2507      2  ...        NaT        NaT
BOROUGH                         2507      5  ...        NaT        NaT
NEIGHBORHOOD                    2507      7  ...        NaT        NaT
BUILDING_CLASS_AT_TIME_OF_SALE  2507     11  ...        NaT        NaT
BUILDING_CLASS_AT_PRESENT       2507     13  ...        NaT        NaT
SALE_DATE                       2507     68  ... 2019-01-01 2019-03-30
LAND_SQUARE_FEET                2507    887  ...        NaT        NaT
ADDRESS                         2507   2497  ...        NaT        NaT

[8 rows x 6 columns]

In [0]:
df_subset.nunique()

BOROUGH                              5
NEIGHBORHOOD                         7
TAX_CLASS_AT_PRESENT                 2
BUILDING_CLASS_AT_PRESENT           13
ADDRESS                           3135
RESIDENTIAL_UNITS                    3
COMMERCIAL_UNITS                     3
TOTAL_UNITS                          4
LAND_SQUARE_FEET                  1035
GROSS_SQUARE_FEET                 1050
YEAR_BUILT                          89
BUILDING_CLASS_AT_TIME_OF_SALE      11
SALE_PRICE                        1000
SALE_DATE                           91
dtype: int64

In [0]:
high_unique_number = [  'SALE_DATE', 'ADDRESS','LAND_SQUARE_FEET', 'BUILDING_CLASS_AT_PRESENT', 'BUILDING_CLASS_AT_TIME_OF_SALE']
target = 'SALE_PRICE'
features = train.columns.drop([target] + high_unique_number)

In [0]:
X_train = train[features]
y_train = train[target]
X_test = test[features]
y_test = test[target]

In [0]:
import category_encoders as ce 
encoder = ce.OneHotEncoder(use_cat_names = True)
X_train = encoder.fit_transform(X_train)

In [0]:
print(X_train.shape)
X_train.head()

(2507, 19)


BOROUGH_3  BOROUGH_4  ...  GROSS_SQUARE_FEET  YEAR_BUILT
44           1          0  ...             1325.0      1930.0
61           0          1  ...             2001.0      1940.0
78           0          0  ...             2043.0      1925.0
108          1          0  ...             2680.0      1899.0
111          1          0  ...             1872.0      1940.0

[5 rows x 19 columns]

In [0]:
X_test = encoder.transform(X_test)


In [0]:
X_test.head()

BOROUGH_3  BOROUGH_4  ...  GROSS_SQUARE_FEET  YEAR_BUILT
18235          0          0  ...             2272.0      1930.0
18239          0          0  ...              720.0      1935.0
18244          1          0  ...             2210.0      1925.0
18280          1          0  ...             1520.0      1915.0
18285          1          0  ...              840.0      1925.0

[5 rows x 19 columns]

In [0]:
# Do feature selection with SelectKBest
from sklearn.feature_selection import SelectKBest, f_regression
selector = SelectKBest(score_func = f_regression, k = 'all')
X_train_selected = selector.fit_transform(X_train, y_train)


In [0]:
print(X_train_selected)

[[1.000e+00 0.000e+00 0.000e+00 ... 1.000e+00 1.325e+03 1.930e+03]
 [0.000e+00 1.000e+00 0.000e+00 ... 1.000e+00 2.001e+03 1.940e+03]
 [0.000e+00 0.000e+00 1.000e+00 ... 1.000e+00 2.043e+03 1.925e+03]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 1.000e+00 1.807e+03 2.018e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 1.000e+00 6.210e+02 1.930e+03]
 [0.000e+00 1.000e+00 0.000e+00 ... 1.000e+00 1.163e+03 1.950e+03]]


In [0]:
X_test_selected = selector.transform(X_test)


In [0]:
X_train_selected.shape, X_test_selected.shape

((2507, 19), (644, 19))

In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
regression = LinearRegression()
regression.fit(X_train, y_train)
X_train_predict = regression.predict(X_train)

In [0]:
X_train_predict

array([738457.373732  , 749629.26416469, 579613.32399859, ...,
       619217.82747079, 323051.00585993, 567553.43319602])

In [0]:
X_test_predict = regression.predict(X_test) 

In [0]:
mae_train = mean_absolute_error(y_train, X_train_predict)
mae_test = mean_absolute_error(y_test, X_test_predict)
print(f'Train Mean Absolute Error: ${mae_train:,.0f} \n')
print(f'Test Mean Absolute Error: ${mae_test:,.0f} \n')

Train Mean Absolute Error: $168,943 

Test Mean Absolute Error: $173,732 



In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

for k in range(1, len(X_train.columns)+1):
    print(f'{k} features')
    
    selector = SelectKBest(score_func=f_regression, k=k)
    X_train_selected = selector.fit_transform(X_train, y_train)
    X_test_selected = selector.transform(X_test)

    model = LinearRegression()
    model.fit(X_train_selected, y_train)
    y_pred = model.predict(X_test_selected)
    mae = mean_absolute_error(y_test, y_pred)
    print(f'Test Mean Absolute Error: ${mae:,.0f} \n')

1 features
Test Mean Absolute Error: $183,641 

2 features
Test Mean Absolute Error: $184,337 

3 features
Test Mean Absolute Error: $178,680 

4 features
Test Mean Absolute Error: $177,170 

5 features
Test Mean Absolute Error: $176,890 

6 features
Test Mean Absolute Error: $176,547 

7 features
Test Mean Absolute Error: $175,733 

8 features
Test Mean Absolute Error: $175,695 

9 features
Test Mean Absolute Error: $176,756 

10 features
Test Mean Absolute Error: $173,165 

11 features
Test Mean Absolute Error: $173,162 

12 features
Test Mean Absolute Error: $173,162 

13 features
Test Mean Absolute Error: $173,050 

14 features
Test Mean Absolute Error: $173,002 

15 features
Test Mean Absolute Error: $173,844 

16 features
Test Mean Absolute Error: $173,845 

17 features
Test Mean Absolute Error: $173,732 

18 features
Test Mean Absolute Error: $173,732 

19 features
Test Mean Absolute Error: $173,732 



In [0]:
regression.coef_, regression.intercept_

(array([ 1.48212042e+05,  5.70100416e+03, -1.67978952e+05, -1.11068721e+05,
         1.25134627e+05, -9.99914936e+04,  1.33605408e+05, -4.22285890e+05,
        -3.22225233e+05,  4.01890095e+05,  1.04353795e+05,  2.04653317e+05,
        -4.90438811e+04,  4.90438811e+04, -4.90438811e+04,  5.04574690e+04,
         1.41358789e+03,  2.21769326e+02,  3.76686381e+02]),
 -233938.07204463077)

In [0]:
#Fit a ridge regression model with multiple features. Use the normalize=True parameter (or do feature scaling beforehand — use the scaler's fit_transform method with the train set, and the scaler's transform method with the test set)
alphas = [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
from sklearn.linear_model import RidgeCV
ridge = RidgeCV(alphas = alphas, normalize = True)
ridge.fit(X_train_selected, y_train)

y_pred = ridge.predict(X_test_selected)
mae = mean_absolute_error(y_test, y_pred)
print(f'Test Mean Absolute Error: ${mae:,.0f} \n')

Test Mean Absolute Error: $173,693 



In [0]:
#Get mean absolute error for the test set.
#As always, commit your notebook to your fork of the GitHub repo.